### ISSUE TITLE
Assert-StringEqual : A positional parameter cannot be found that accepts argument 'bde'

### ISSUE THREAD

**Issue by irwins** [nohwnd/Assertions#4]
![image](https://cloud.githubusercontent.com/assets/10112589/22689151/ece6d18c-ed2f-11e6-9411-6e2bbb956814.png)

**Comment by irwins** [comment]
![image](https://cloud.githubusercontent.com/assets/10112589/22689200/1f312e3a-ed30-11e6-8c64-9734bc8409ef.png)

**Comment by irwins** [comment]
![image](https://cloud.githubusercontent.com/assets/10112589/22689232/43e02ef2-ed30-11e6-8dc5-f36af20f0cc7.png)

This works as expected

**Comment by nohwnd** [comment]
@irwins fixed, thanks for reporting, check out all the new features :)
